version: '3'

services:
  dev:
    build: .
    command: python -m flask run -p 8000 -h 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      FLASK_DEBUG: "1"
      FLASK_APP: "tmdb"
      FLASK_ENV: "development"
      TMDB_BASE_URL: "https://api.themoviedb.org/3"
      TMDB_API_KEY: "1f54bd990f1cdfb230adb312546d765d"

  prod:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 tmdb:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      TMDB_BASE_URL: "https://api.themoviedb.org/3"
      TMDB_API_KEY: "1f54bd990f1cdfb230adb312546d765d"
