version: '3'

services:
  api:
    build: .
    command: python -m flask run -p 8000 -h 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=tmdb
      - FLASK_ENV=development
